---
services:

  mariadb:
    container_name: sql-primary
    image: mariadb:11.4
    restart: unless-stopped
    volumes:
      - /srv/docker/sql-primary:/var/lib/mysql
      - shared-data:/data/backup
      - ./dump.sh:/dump.sh
    environment:
      MARIADB_ROOT_PASSWORD: toto
      MARIADB_DATABASE: wpdb
      MARIADB_USER: xav
      MARIADB_PASSWORD: titi
    networks:
      - db-network

  wordpress:
    container_name: wp
    image: wordpress:6.6
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: xav
      WORDPRESS_DB_PASSWORD: titi
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - /srv/docker/wordpress:/var/www/html
    networks:
      - db-network
      - front-network

#  mariadb2:
#    container_name: sql-svg
#    image: mariadb:11.4
#    restart: unless-stopped
#    volumes:
#      - /srv/docker/dbdata2:/var/lib/mysql
#      - shared-data:/data/backup
#      - ./restore.sh:/restore.sh
#    environment:
#      MARIADB_ROOT_PASSWORD: toto
#      MARIADB_DATABASE: mydb
#      MARIADB_USER: xav
#      MARIADB_PASSWORD: titi

volumes:
  shared-data:

networks:
  db-network:
    internal: true
  front-network:
